name: Build and Deploy Staging to Github Pages

# manually trigger a workflow for now
on: workflow_dispatch
# on:
#   push:
#     branches:
#       - staging  
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout staging 
        uses: actions/checkout@v3
        with:
          ref: staging
      - name: Set env vars 
        shell: bash
        run: |
          echo "DEPLOY_PREFIX=website-staging/staging" >> $GITHUB_ENV
          echo "SITE_URL=https://usds.github.io/website-staging" >> $GITHUB_ENV
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1