name: wesite staging deployment

# Build:
  ## Setup Pages
  ## Upload Artifact
# Move Result Files
# Clone the staging repo 
# Move the built files, commit them
# Push to website-staging repository 

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Staging
        uses: actions/checkout@v3
        with: 
          ref: staging
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site   
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v1
      - name: Move result files 
        run: |
          pwd
          mkdir output 
          ls -lah
          rm -rf .git
          cp -r _site output
        
      #     shopt -s extglob dotglob
           
      #     pwd
      #     mkdir staging
      #     ls -lah
      #     mv !(staging) staging
      - name: Clone the staging repo 
        uses: actions/checkout@v3
        with: 
          repository: usds/website-staging
          token: ${{ secrets.PAT }}
          ref: 'main'
          path: website-staging
      - name: Move the built files, commit them
        run: |
          cd website-staging
      - name: Push to website-staging repository 
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.STAGING_KEY }}
        with:
          source-directory: output 
          destination-github-username: 'usds'
          destination-repository-name: 'website-staging'
          target-branch: main
